### PR TITLE
Changes to support generating the sokol-fetch bindings in zig

### PR DESCRIPTION
**Pull request by trace-andreason**
Related to this issue: https://github.com/floooh/sokol-zig/issues/63. Not ready to be merged, just thought it might be helpful for that discussion

### CODE REVIEW

**Comment by floooh** [comment]
...that fetch callback should actually be handled here:

https://github.com/floooh/sokol/blob/f70cc07f0fcd763ab6ff0171a6b8fe1dca3ed367/bindgen/gen_zig.py#L339-L340

...I'm currently investigating why it isn't...

**Comment by floooh** [comment]
Aha, because it's a typedef in the sokol_fetch.h header, and that's not detected in the bindings generation script.

If I remove the `sfetch_callback_t` typedef from sokol_fetch.h and replace the callback declaration in `sfetch_request_t` to this:

```c
typedef struct sfetch_request_t {
    ...
    void (*callback) (const sfetch_response_t*);
    ...
} sfetch_request_t;
```

...it works, and generates the following Zig struct:

```zig
pub const Request = extern struct {
    channel: u32 = 0,
    path: [*c]const u8 = null,
    callback: ?*const fn ([*c]const Response) callconv(.C) void = null,
    chunk_size: u32 = 0,
    buffer: Range = .{},
    user_data: Range = .{},
};
```

...can you integrate this sokol_fetch.h change in your PR and remove your "manual exception hack"?

**Comment by trace-andreason** [comment]
made those changes

**Comment by floooh** [comment]
...for the `sfetch_desc` override I would actually prefer `sfetch_get_desc` which would then end up as `fetch.getDesc()` on the Zig side.

For `continue` maybe `resume`? Since it's "resuming from paused state".

...tbh, `sfetch_resume()` would also be a good change in the C header.

**Comment by floooh** [comment]
...one other thing I currently wonder about is whether we should restrict sokol_fetch.h to the Zig bindings for now, e.g. remove the sokol_fetch item from the tasks array in gen_all.py, and instead do this down in the gen_zig block:

```python
zig_tasks = [
    *tasks,
    [ '../util/sokol_fetch.h', 'sfetch_', [] ],
]
for task in zig_tasks:
   ...
```

**Comment by trace-andreason** [comment]
turns out resume is also reserved

**Comment by trace-andreason** [comment]
I went ahead and named it `continue_fetching`, but open to any other suggestion. All other comments are incorporated.

**Comment by floooh** [comment]
Yeah `continue_fetching` is fine :)

**Comment by trace-andreason** [comment]
bindings build step is going to fail until `sokol_fetch.c` file is added to the repo

**Comment by floooh** [comment]
Yep, I think I can take over from here. I'll also need to do a quick check if the dropped typedef breaks anything (I don't think so, but technically it's a breaking change). I'll try to look into it later today.

**Comment by floooh** [comment]
Zig master might have had a breaking change in LazyPath. I'm looking into it.

**Comment by floooh** [comment]
Ok, took a bit longer then I had hoped, but the sokol-zig build.zig is now fixed for the current zig head version.

**Comment by floooh** [comment]
I'll go ahead and merge this PR.

The next step would then be in sokol-zig again to add the C source file to build.zig here:

https://github.com/floooh/sokol-zig/blob/7d569775df73d1e869a1df12dfc647e56c7cb77a/build.zig#L265

...and the fetch.zig module here:

https://github.com/floooh/sokol-zig/blob/7d569775df73d1e869a1df12dfc647e56c7cb77a/src/sokol/sokol.zig#L9

Ideally we would also have a new sample, but I can do that at a later time.

**Comment by floooh** [comment]
...also added a little blurb to the CHANGELOG about the theoretically breaking change in sokol_fetch.h

**Pull request merged**
