### PR TITLE
sokol_app raspberry pi 

### PR DESCRIPTION
**Pull request by septag**
here's a draft version of rpi.  #195 

I didn't find any convenient way of finding the platform with compiler defines, so I defined `__RPI__` in the build system.

looking forward for your input and suggestions.

### CODE REVIEW

**Comment by floooh** [comment]
I'll try to have a look soon-ish, as with the sokol_audio.h PR it can take a little while though, apologies in advance :)

**Comment by meshula** [comment]
> I didn't find any convenient way of finding the platform with compiler defines, so I defined __RPI__ in the build system.

I've searched as well, and can't find anything.

**Comment by floooh** [comment]
I've actually thought today that I should get myself a Pi4 ;)

**Comment by meshula** [comment]
It's really fun to hack with.

**Comment by AndrewCapon** [comment]
Hi guys, is PI support going to be coming to Sokol?

**Comment by floooh** [comment]
@AndrewCapon: It's currently not a high priority. The X11/GLX-backend in sokol_app.h might actually work on modern Raspis (I'm currently away from my RPi4 and can't check though). The port in this PR is EGL+VideoCore based which would also work without window system.

(but I'll go ahead and close the PR now because it has diverged too much from the current code, it's probably easier to start from scratch).

**Comment by colesnicov** [comment]
> here's a draft version of rpi. #195
> 
> I didn't find any convenient way of finding the platform with compiler defines, so I defined `__RPI__` in the build system.
> 
> looking forward for your input and suggestions.

What model RPI you are use?

**Pull request closed without merging**
