### PR TITLE
Added emscripten support for the Nim's gen script

### PR DESCRIPTION
**Pull request by Nazariglez**
Related to https://github.com/floooh/sokol-nim/pull/31

### CODE REVIEW

**Comment by floooh** [comment]
Thanks for the PRs! I'm a bit busy atm with this Chrome WebGL2 regressions thingy (there goes the weekend lol), but I'll try to focus on those PRs some time next week.

**Comment by floooh** [comment]
NOTE: that CI tests are expected to break because they don't have the changes in sokol-nim, don't worry about that.

**Comment by Nazariglez** [comment]
There is nor rush at all, thanks @floooh!

**Comment by floooh** [comment]
...checking now whether the CI runs through with the changes in sokol-nim merged, this will take a little bit...

**Comment by floooh** [comment]
...ok actually got a real error in the CI pipeline now:

```
sokol/gfx.nim(2032, 5) Error: expected: ':', but got: 'keyword when'
```

**Comment by floooh** [comment]
There's this difference between the generated version and sokol-nim:

```
diff --git a/src/sokol/gfx.nim b/src/sokol/gfx.nim
index bc8f184..b4758a0 100644
--- a/src/sokol/gfx.nim
+++ b/src/sokol/gfx.nim
@@ -2006,7 +2006,7 @@ when defined emscripten:
   const d3d11* = false
   const metal* = false
   const emscripten* = true
-elif defined gl:
+elif when defined gl:
   const gl*    = true
   const d3d11* = false
   const metal* = false
```

I guess that `when` should be there, I'll try to fix that locally.

**Comment by floooh** [comment]
Ok, I did this minor fix and then merged: https://github.com/floooh/sokol/commit/b073c61c6e1d27d3e8e40ad83ebca3bad62a9b01

I didn't actually try to build for Emscripten, only for native macOS.

I'll add a little blurb to the changelog next.

Thanks for the PR!

**Pull request merged**
