### PR TITLE
Adds SOKOL_NOAPI to WIN32

### PR DESCRIPTION
**Pull request by pplux**
Minimal changes to support "NO_API" on windows.

### CODE REVIEW

**Comment by floooh** [comment]
Those CI errors are unrelated. Looks like the Spine C API has changed. I'll look into it.

**Comment by floooh** [comment]
Ok, I pinned the spine version used in the tests to 4.1 in the master branch.

Can you either do a merge from master or rebase your branch on top of latest master?

**Comment by pplux** [comment]
Indeed, definitely not a revolutionizing change by any means, but very handy if you need to step out of the supported render backends (like our use case with vulkan/webgpu-native). Shoutout to @castano who actually did the work.

**Comment by floooh** [comment]
Ok merged, thanks! I'll also add a small changelog blurb.

**Comment by dortamiguel** [comment]
@pplux did you succeed to create a vulkan context using sokol?

**Comment by pplux** [comment]
@dortamiguel Haven't tried, I use it mostly for webgpu contexts, and it works great. I would assume that a vulkan context should be fairly similar, but I haven't tried.

**Pull request merged**
