### PR TITLE
sapp_toggle_fullscreen(), implemented for win32

### PR DESCRIPTION
**Pull request by mattiasljungstrom**
Implements sapp_toggle_fullscreen(). Each call changes window style and layout to either windowed or fullscreen based on the value in _sapp.desc.fullscreen.

The code tries to center the window on switch from fullscreen. If the size of the window is too large for the current monitor, it uses the monitor size.

Not sure if you want this or not, but I figured I'll do a pull request. I've only implemented this for win32, can take a look at macOS later if you want to keep it.

I've only tested this under latest Win10.

### CODE REVIEW

**Comment by mattiasljungstrom** [comment]
Wanted to check if you think this is something that should be in sokol or not? Otherwise I'll keep it in my sokol_ext.h file.

**Comment by floooh** [comment]
> Wanted to check if you think this is something that should be in sokol or not? Otherwise I'll keep it in my sokol_ext.h file.

It's a good addition, I'm just lagging behind with the Pull Requests :)

I'm not sure yet if a toggle function is enough, usually I have at least one other function which explicitely sets to fullscreen or windowed (and is a no-op if it's already in the right state). I'll try to catch up on PR's after I'm happy with the new sokol_debugtext.h header.

**Comment by floooh** [comment]
A bit of feedback:

- The function shouldn't modify the desc.fullscreen flag because the existing function ```sapp_query_desc()``` is expected to return the original desc struct. So there should be a new "mutable: _sapp.fullscreen flag which gets its initial value from ```_sapp.desc.fullscreen```. The other places where ```_sapp.desc.fullscreen``` is inspected should be changed to look at the new ```_sapp.fullscreen``` flag instead.

- A new function ```bool sapp_is_fullscreen(void)``` which returns the _sapp.fullscreen flag. That way that "explicit" function I mentioned in the above comment isn't needed, instead an application can check the sapp_is_fullscreen() return value to decide whether sapp_toggle_fullscreen needs to be called or not.

**Comment by mattiasljungstrom** [comment]
The feedback makes sense, will update the code.

This is maybe another ticket, but it's related: the size of the non-fullscreen window is in window size, not in render target size. So, if you ask for a 1920x1080 on windows, it's instead 1900x1071 or something in render target size. What's your take on this? One option would be to query windows for the size of the borders, etc. and add them all up.

**Comment by mattiasljungstrom** [comment]
Re my last comment, I noticed that this is correctly handled if the window is setup as windowed directly. Will investigate more why it's incorrect when toggled.

**Comment by mattiasljungstrom** [comment]
Updated based on your feedback, and fixed sizing bug. Tested with high dpi as well.

**Comment by floooh** [comment]
There's a small problem with using designated initialization

```
MONITORINFO minfo = { .cbSize = sizeof(MONITORINFO) };
```

...but I'll fix that manually after the merge.

**Comment by floooh** [comment]
...and another small thing I'm going to "fix in post"

```c
... _sapp_win32_toggle_fullscreen() {
```

should be
```c
... _sapp_win32_toggle_fullscreen(void) {
```

**Comment by floooh** [comment]
...ok, another small fix I did (only slightly related) is to improve the default-value replacement in sapp_desc a bit, so that the _sapp_def() macros in _sapp_win32_toggle_fullscreen() are not needed:

https://github.com/floooh/sokol/commit/061b56ead450de774a4b6d193af8e2ccf53ac42b

**Comment by floooh** [comment]
...oh, and I added a test button to the imgui-highdpi-sapp sample to toggle windowed/fullscreen :)

And I forgot: Thanks for the PR :)

...I'll see if I can also add support for macOS while I'm at it...

**Comment by mattiasljungstrom** [comment]
cool, thanks for merging and fixing!

**Pull request merged**
