### PR TITLE
added cimgui wrapper and gfx debugger

### PR DESCRIPTION
**Pull request by prime31**
I'm not sure if you're interested in something like this, but I figured I'd send over a PR and you can either accept it or close it. I converted the sokol Dear ImGui renderer and gfx debugger over to work with cimgui for projects that don't use C++.

### CODE REVIEW

**Comment by floooh** [comment]
Hi @prime31, yes, this is extremely cool! I wasn't sure how closely cimgui follows the latest imgui versions, AFAIK in the past it was always quite a bit behind. But it looks it is now automatically generated, so everything good :)

I'll play around a bit with your PR and will also add a cimgui sample to the sokol-samples repo (and at least one using the cimgui gfx debugger), so it'll be a few days until I merge the PR.

**Comment by floooh** [comment]
...cimgui sample added: https://floooh.github.io/sokol-html5/wasm/cimgui-sapp.html

**Comment by floooh** [comment]
...and the microui-sample now uses sokol_gfx_cimgui.h for its debugging-UI:

https://floooh.github.io/sokol-html5/wasm/sgl-microui-sapp-ui.html

**Comment by prime31** [comment]
Woohoo! Now we get to stay in C mode with its beautiful compound literal syntax for structs everywhere ;)

**Pull request merged**
