### PR TITLE
Linux EGL and GLES2/3 support

### PR DESCRIPTION
**Pull request by billzez**
This allows Linux to use EGL instead of GLX.  GLCORE33, GLES2, and GLES3 are supported.

SOKOL_GLES2/3 will select EGL by default.  SOKOL_GLCORE33 defautls to GLX unless SOKOL_FORCE_EGL is defined.

Tested on Intel Adler Lake and Raspberry Pi 4.

### CODE REVIEW

**Comment by floooh** [comment]
I only quickly glanced over it, but looks like a nicely compact and clean change :)

I'm without a Linux laptop this week, but I'll try to give it a whirl next week.

**Comment by mckaygerhard** [comment]
this means more hardware are supported, but by example openchrome gpus will be supported? that already has limited opengl support in older linuxes?

**Comment by darltrash** [comment]
> this means more hardware are supported, but by example openchrome gpus will be supported? that already has limited opengl support in older linuxes?

In theory, it should support anything with GLES2 upwards

**Comment by Newbytee** [comment]
Works fine on my OpenGL ES 2.0-capable Samsung Galaxy Note 10.1 running Linux/postmarketOS:

JPEG_20220920_152134_7598356759889846860

Nice job!

**Comment by floooh** [comment]
Ok, I'll start looking into this now. Rough plan is:
- get familiar with the code
- add the new build config to the compilation test and static code analyzer scripts
- add a new build config to the sokol samples
- merge

**Comment by floooh** [comment]
I'm getting two warnings with the (fairly aggressive) sokol-samples compile settings, I'll fix those in the merge-branch I have created:

```c
/home/floh/projects/sokol/sokol_app.h: In function ‘_sapp_egl_init’:
/home/floh/projects/sokol/sokol_app.h:11577:37: warning: conversion to ‘VisualID’ {aka ‘long unsigned int’} from ‘EGLint’ {aka ‘int’} may change the sign of the result [-Wsign-conversion]
11577 |     visual_info_template.visualid = visual_id;
      |                                     ^~~~~~~~~
In file included from /home/floh/projects/sokol-samples/libs/sokol/sokol.c:8:
/home/floh/projects/sokol/sokol_app.h:11565:80: warning: ‘n’ may be used uninitialized [-Wmaybe-uninitialized]
11558 |         if (eglGetConfigAttrib(_sapp.egl.display, c, EGL_RED_SIZE, &r) &&
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~       
11559 |             eglGetConfigAttrib(_sapp.egl.display, c, EGL_GREEN_SIZE, &g) &&
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
11560 |             eglGetConfigAttrib(_sapp.egl.display, c, EGL_BLUE_SIZE, &b) &&
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      
11561 |             eglGetConfigAttrib(_sapp.egl.display, c, EGL_ALPHA_SIZE, &a) &&
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
11562 |             eglGetConfigAttrib(_sapp.egl.display, c, EGL_DEPTH_SIZE, &d) &&
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     
11563 |             eglGetConfigAttrib(_sapp.egl.display, c, EGL_STENCIL_SIZE, &s) &&
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
11564 |             eglGetConfigAttrib(_sapp.egl.display, c, EGL_SAMPLES, &s) &&
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        
11565 |             r == 8 && g == 8 && b == 8 && a == alpha_size && d == 24 && s == 8 && n == sample_count) {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```

**Comment by floooh** [comment]
...and merged!

**Pull request merged**
