### PR TITLE
Pixel format info

### PR DESCRIPTION
**Pull request by amerkoleci**
This initially implements #112 .
Tell me if you like the API so I can add to other backends.

### CODE REVIEW

**Comment by floooh** [comment]
Yes this looks good!

Two comments:

- Calls which require non-GLES2 features like this: https://github.com/floooh/sokol/pull/154/files#diff-a8b646082914484fa2639b5ad5947b55R4066 need to behind a compile- *and* runtime-check:

```c
#if !defined(SOKOL_GLES2)
if (!_sg.gl.gles2) {
   ...
}
#endif 
```

- I think there should be another query-info-member ```max_layers``` for the max number of array-texture layers, queried from GL with GL_MAX_ARRAY_TEXTURE_LAYERS. This must also be behind a "not GLES2" check like above.

**Comment by amerkoleci** [comment]
Can you take look if it's ok?

**Comment by floooh** [comment]
Looking over the changes it looks good to me (I haven't merged or run the code).

**Comment by floooh** [comment]
Hi @amerkoleci, I have merged this PR into the branch: https://github.com/floooh/sokol/tree/pixelformat, and will continue working there on the whole "pixel format cleanup topic". Your commit history is intact so I guess that's ok ;)

**Pull request closed without merging**
