### PR TITLE
Fixed typos in sokol_gfx

### PR DESCRIPTION
**Pull request by DctrNoob**
This PR addresses a few typos in sokol_gfx.h. I hope you also don't mind the addition of `.DS_Store` to `.gitignore`.

### CODE REVIEW

**Comment by floooh** [comment]
Thanks much appreciated! 

I noticed that I'm prone to this sort of typo (both for the new types `sg_environment` and `sg_attachment` and was actually considering finding different names where the likelyhood of those typos is lower :/

I have one request though: the commit history in this PR looks a bit scary despite the small diff, can you try to build a cleaner PR which only has that single fix commit? (I don't want to risk all those commit messages ending up in the master branch history.

I'm not sure how to best do this if you already have your own fork though. Probably creating a new branch difrectly from upstream master?

**Comment by DctrNoob** [comment]
Usually, I would not have gone to the length of creating a PR for a couple of typos but one of them was in a C++ function signature and that bothered me a lot. =)

Yeah, the commit history sucks, sorry. I'll try your suggestion of creating a new branch from upstream/master.

**Comment by floooh** [comment]
...if that doesn't work I can probably cherry-pick the one commit that matters outside the Github PR workflow. Let me know how it goes :)

**Comment by DctrNoob** [comment]
Yeah, so what if you just cherry-pick commit a8938fdcb7fb03f997e96756d20ce018091c61d2. Or just redo the typo fixes directly in the master branch.

**Comment by floooh** [comment]
Trying to cherry-pick now :)

**Comment by floooh** [comment]
Ok that worked :) Closing this PR now.

https://github.com/floooh/sokol/commit/db32cf409a9eb984e1ababa96e243f141c7f40ed

**Pull request closed without merging**
