### PR TITLE
Border color for image in DirectX

### PR DESCRIPTION
**Pull request by martincohen**
- Added support for `CLAMP_TO_BORDER` in `sg_image` for DirectX.
- Added feature `image_border_color`, now only true for DirectX.

https://github.com/floooh/sokol/issues/204

### CODE REVIEW

**Comment by floooh** [comment]
...btw, not sure if you're aware of it, but the whole PR workflow works much better when you create a separate branch (I noticed that the PR is created from a forked master branch) :)

I'm starting to look into Metal and GL support now...

**Comment by floooh** [comment]
...I'll be working on this branch, you can continue adding changes to this PR, I'll track and merge those to my branch.

**Comment by martincohen** [comment]
> ...btw, not sure if you're aware of it, but the whole PR workflow works much better when you create a separate branch (I noticed that the PR is created from a forked master branch) :)
> 
> I'm starting to look into Metal and GL support now...

I wasn't a contributor before, so forking was the only way. And since I've had it setup from the first PR, I've used it for this PR as well. :)

**Comment by floooh** [comment]
> I wasn't a contributor before, so forking was the only way. And since I've had it setup from the first PR, I've used it for this PR as well. :)

Ah, no, I mean first do a fork of course, but then create a branch to work on just for that PR. After the PR is merged, that branch can be deleted.

Then when starting work on another PR, first bring the forked repo's master branch uptodate by merging changes from "upstream", and create a new branch.

But I guess if you were not running into trouble working on the master branch that's fine, from my side I haven't had problems (for instance when merging the PR) either yet :)

**Comment by martincohen** [comment]
Yah, working from master was without a problem. :)

**Comment by floooh** [comment]
Stumbled over a little problem:

Metal only allows 3 hardwired border colors: black, white and transparent:

https://developer.apple.com/documentation/metal/mtlsamplerbordercolor?language=objc

WebGPU doesn't seem to support clamp-to-border at all:

https://gpuweb.github.io/gpuweb/#samplers

Opinions? Would your use-case work with one of the 3 hardwired border colors from Metal?

**Comment by floooh** [comment]
PS: since you mention in https://github.com/floooh/sokol/issues/204 that you use a white border, I think I'll just go ahead and use the "3 color approach", the ```float border_color[4]``` member in sg_image_desc would be replaced with an enum ```sg_border_color``` with SG_BORDERCOLOR_TRANSPARENT_BLACK and SG_BORDERCOLOR_OPAQUE_BLACK, SG_BORDERCOLOR_OPAQUE_WHITE.

**Comment by floooh** [comment]
...oh, and border color also isn't available at all in Metal on iOS... :(

That's the reason why WebGPU doesn't implement it.

What a mess...

**Comment by martincohen** [comment]
@floooh White is perfectly sufficient. I'm also thinking whether to revert back and keep the library simple...

**Comment by floooh** [comment]
I decided to go on with the black/white/transparent version. Metal is done, I'm currently working on the GL version. It's very little code and doesn't change the public API (except for some new members in structs), so it's ok to keep it in, even though it's not really useful for cross-platform usage. I also started an extremely simple example:

Screen Shot 2019-09-07 at 2 34 34 PM

I also decided to fall back to clamp-to-edge if the feature isn't available without a hard validation error (but applications can check the sg_features flag of course.

**Comment by floooh** [comment]
Closing this PR now, as it's become the base of this PR: https://github.com/floooh/sokol/pull/209

**Comment by martincohen** [comment]
> Closing this PR now, as it's become the base of this PR: #209

Sure thing!

**Pull request closed without merging**
