### PR TITLE
Fix _sapp_android_init_egl() failure on Xiaomi Redmi 6A device 

### PR DESCRIPTION
**Pull request by elix22**
This failure might also happen on other Android devices.

### CODE REVIEW

**Comment by fabiopolimeni** [comment]
Just to let you know this also worked for me on the _RETROID_ 2+ (Android 9). It would fail to create the EGL surface otherwise. It looks a simple fix/change, maybe worth a merge?

**Comment by floooh** [comment]
Yes, makes sense, thanks for bringing the PR to my attention again. I need to look into a sokol_audio.h problem first and then will look into this PR.

**Comment by floooh** [comment]
I haven't merged the PR (since it's outdated and also contains unrelated sokol_audio.h changes, but instead I added this to the sokol_app.h backend:

```c
        EGL_SURFACE_TYPE, EGL_WINDOW_BIT,
        #if defined(SOKOL_GLES3)
		    EGL_RENDERABLE_TYPE, _sapp.desc.gl_force_gles2?EGL_OPENGL_ES2_BIT:EGL_OPENGL_ES3_BIT,
        #else
		    EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
        #endif
        EGL_RED_SIZE, 8,
```

(note how the gl_force_gles2 config flag is checked, this also happens below when creating the GL context)

Also see commit https://github.com/floooh/sokol/commit/67c321cdbb9c46e2944e77ca7a4ba3a611b80555

Unfortunately I currently don't have a way to test this on my (Pixel4) phone, since I don't seem to have an USB to UCB-C cable, I'll see if I can buy one tomorrow.

**Comment by floooh** [comment]
Ok, tested a bit on my Pixel4 with the sokol-samples, and at least there it's working.

**Pull request closed without merging**
